server:
    port: 19336

spring:
    profiles:
        active: dev
    application:
        name: speed up security check ca
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: ALWAYS
    messages:
        basename: i18n/messages

mybatis:
    mapper-locations:
        - classpath:mappers/*.xml

logging:
    pattern:
        console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%thread]){faint} %clr(%-40.40logger{39}){cyan} %L %clr(:){faint} %m%n"
    level:
        root: INFO

front-end-address:
    verification: /verification