spring:
    datasource:
        url: jdbc:mysql://localhost:3309/security_screening?useUnicode=true&characterEncoding=utf8
        hikari:
            driver-class-name: com.mysql.cj.jdbc.Driver
            username: root
            password: 123456

mail:
    sender: iamnotyourspy@gmail.com
    password: kvhq jqeu ilms qwhb

front-end-address:
    base: http://localhost:3400

secret-for-updating:
    ThisIsPowerVergil